// declare constansts to be used to determine type for async reducer actions
const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
const SIGN_IN_FAIL = "SIGN_IN_FAIL";

const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
const SIGN_UP_FAIL = "SIGN_UP_FAIL";

const SIGN_OUT = "SIGN_OUT"

const GET_PROJECTS_REQUEST = "GET_PROJECTS_REQUEST";
const GET_PROJECTS_SUCCESS = "GET_PROJECTS_SUCCESS";
const GET_PROJECTS_FAIL = "GET_PROJECTS_FAIL";

export {
    SIGN_IN_REQUEST, SIGN_IN_SUCCESS, SIGN_IN_FAIL, SIGN_UP_REQUEST, SIGN_UP_SUCCESS, SIGN_UP_FAIL, SIGN_OUT,
    GET_PROJECTS_FAIL, GET_PROJECTS_REQUEST, GET_PROJECTS_SUCCESS,
}